variable "name" {
  type        = string
  description = "Name for VM in Proxmox."
}

variable "proxmox_url" {
  type        = string
  sensitive   = true
  description = "The URL for Proxmox. The module will automatically append `/api2/json` for the API"
}

variable "proxmox_tls_insecure" {
  type        = bool
  default     = true
  description = "Whether the Proxmox TLS certificate is unverifiable."
}

variable "proxmox_target_node" {
  type        = string
  default     = "pve"
  description = "The target proxmox node name to deploy to."
}

variable "start_on_boot" {
  type        = bool
  default     = true
  description = "Set to allow the guest to be started when Proxmox boots."
}

variable "enable_qemu_agent" {
  type        = bool
  default     = true
  description = "Set to enable the QEMU agent in the guest."
}

variable "memory" {
  type        = number
  default     = 512
  description = "The amount of memory to give the VM, in MB."
}

variable "min_memory" {
  type        = number
  default     = 0
  description = "Set to enable minimum memory in MB for ballooning. This option will make `memory` the maximum."
}

variable "cpu_cores" {
  type        = number
  default     = 4
  description = "The number of CPU cores to give the VM."
}

variable "disks" {
  type        = list(object({ type = string, storage = string, size = string }))
  description = "The disks to add to the VM."
}

variable "network_model" {
  type        = string
  default     = "virtio"
  description = "Set the network interface model. Options: `e1000`, `e1000-82540em`, `e1000-82544gc`, `e1000-82545em`, `i82551`, `i82557b`, `i82559er`, `ne2k_isa`, `ne2k_pci`, `pcnet`, `rtl8139`, `virtio`, `vmxnet3`."
}

variable "network_bridge" {
  type        = string
  default     = "vmbr0"
  description = "Set the network interface bridge. Typically `vmbr0`."
}

variable "mac_address" {
  type        = string
  default     = ""
  description = "MAC address of the VM guest. If not set, one will be autogenerated."
}

variable "cloudinit_template_name" {
  type        = string
  default     = "ubuntu-server-20.04-focal"
  description = "Name of the cloud-init template created as per <https://pve.proxmox.com/wiki/Cloud-Init_Support#_preparing_cloud_init_templates>"
}

variable "pve_host" {
  type        = string
  sensitive   = true
  description = "Hostname of SSH session to proxmox to load cloud-init file."
}

variable "pve_user" {
  type        = string
  default     = "ci"
  description = "Username of the user to connect via SSH to proxmox to load cloud-init file."
}

variable "pve_password" {
  type        = string
  sensitive   = true
  description = "Password of the user to connect via SSH to proxmox to load cloud-init file."
}

variable "cloud_init" {
  type        = string
  sensitive   = true
  description = "Content of cloud-init config"
}